- If u want your own video,picture and icon files just delete the demo ones and rename urs to "default1" and paste it into the video folder.
- Remeber the file extentions are MP4,PNG,ICO.
- Anything else wont work.
